"use client";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { FileCheck2, Scale, ShieldCheck } from "lucide-react";
import { useLocale } from "next-intl";

export default function TerminosCondicionesPage() {
  const locale = useLocale();
  const isEs = locale === "es";

  return (
    <div className="min-h-screen flex flex-col bg-[#f4f8f5]">
      <Header />

      <main className="flex-1 pt-32 pb-24 relative overflow-hidden">
        {/* Decoraciones */}
        <div className="absolute -top-48 -right-48 w-[42rem] h-[42rem] bg-emerald-300/20 rounded-full blur-[160px] pointer-events-none" />
        <div className="absolute top-1/3 -left-52 w-[38rem] h-[38rem] bg-cyan-300/15 rounded-full blur-[160px] pointer-events-none" />
        <div className="absolute -bottom-40 right-1/4 w-[34rem] h-[34rem] bg-amber-200/20 rounded-full blur-[140px] pointer-events-none" />

        <div className="container mx-auto px-6 max-w-5xl relative z-10">
          <div className="text-center mb-14 animate-bounce-up">
            <div className="inline-flex items-center gap-2 px-5 py-2.5 bg-emerald-950 text-emerald-50 rounded-full mb-7 font-black text-[10px] uppercase tracking-[0.18em] border border-emerald-800 shadow-lg shadow-emerald-950/10">
              <ShieldCheck className="w-4 h-4 text-emerald-300" />
              {isEs ? "Acuerdos de Servicio" : "Service Agreements"}
            </div>

            <h1 className="text-4xl md:text-6xl font-black font-bricolage text-emerald-950 tracking-tight leading-tight">
              {isEs ? "Términos y Condiciones" : "Terms and Conditions"}
            </h1>

            <p className="mt-5 max-w-2xl mx-auto text-base md:text-lg text-slate-500 font-medium leading-relaxed">
              {isEs
                ? "Consulta las disposiciones que regulan la contratación y el uso de las experiencias y servicios ofrecidos por Oasix."
                : "Review the provisions governing the contracting and use of the experiences and services offered by Oasix."}
            </p>
          </div>

          <div className="bg-white/95 backdrop-blur-xl rounded-[2.5rem] md:rounded-[3.5rem] p-7 md:p-16 shadow-[0_35px_100px_-45px_rgba(6,78,59,0.5)] border border-emerald-950/10 animate-bounce-up delay-100 relative overflow-hidden">
            <div className="absolute -top-32 -right-32 w-96 h-96 bg-emerald-200/20 rounded-full blur-3xl pointer-events-none" />
            <div className="absolute top-1/2 -left-28 w-64 h-64 bg-cyan-200/15 rounded-full blur-3xl pointer-events-none" />

            <div className="relative z-10 prose prose-lg max-w-none prose-headings:font-bricolage prose-headings:font-black prose-headings:text-emerald-950 prose-h2:mt-12 prose-h2:mb-5 prose-h2:pb-4 prose-h2:border-b prose-h2:border-emerald-950/10 prose-p:text-slate-600 prose-p:font-medium prose-p:leading-8 prose-strong:text-emerald-950 prose-li:text-slate-600 prose-li:font-medium prose-li:leading-8 prose-li:marker:text-emerald-600 prose-ul:my-6">
              <div className="not-prose mb-10 grid sm:grid-cols-2 gap-4">
                <div className="flex items-center gap-4 bg-emerald-50 border border-emerald-200 rounded-[1.75rem] p-5">
                  <div className="w-12 h-12 bg-emerald-950 text-emerald-100 rounded-2xl flex items-center justify-center shrink-0">
                    <Scale className="w-6 h-6" strokeWidth={2.5} />
                  </div>

                  <div>
                    <p className="text-[10px] text-emerald-700 font-black uppercase tracking-[0.16em] mb-1">
                      {isEs ? "Marco contractual" : "Contractual Framework"}
                    </p>

                    <p className="text-sm text-emerald-950/70 font-bold leading-relaxed">
                      {isEs
                        ? "Condiciones aplicables a los servicios contratados con Oasix."
                        : "Conditions applicable to services contracted with Oasix."}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-4 bg-amber-50 border border-amber-200 rounded-[1.75rem] p-5">
                  <div className="w-12 h-12 bg-amber-300 text-emerald-950 rounded-2xl flex items-center justify-center shrink-0">
                    <FileCheck2 className="w-6 h-6" strokeWidth={2.5} />
                  </div>

                  <div>
                    <p className="text-[10px] text-amber-800 font-black uppercase tracking-[0.16em] mb-1">
                      {isEs ? "Aceptación" : "Acceptance"}
                    </p>

                    <p className="text-sm text-amber-950/70 font-bold leading-relaxed">
                      {isEs
                        ? "La contratación confirma la aceptación de estas disposiciones."
                        : "Contracting confirms the acceptance of these provisions."}
                    </p>
                  </div>
                </div>
              </div>

              {isEs ? (
                <>
                  <h2>1. Identidad de la empresa</h2>
                  <p><strong>1.1.</strong> El presente documento establece los Términos y Condiciones Generales de Contratación (en adelante, las “Condiciones Generales”) que regulan la relación jurídica entre los usuarios (en adelante, el “Usuario” o los “Usuarios”) y GREATDEN, S.A. DE C.V. (en adelante, “OASIX”), empresa constituida conforme a las leyes mexicanas.</p>
                  <p><strong>1.2. Datos de identificación:</strong></p>
                  <ul>
                    <li><strong>Razón social:</strong> GREATDEN, S.A. DE C.V.</li>
                    <li><strong>Domicilio:</strong> Av. Río Consulado Cto Interior 516, Oficina 102, Col. Tlatilco, Alcaldía Azcapotzalco, C.P. 02860, Ciudad de México.</li>
                    <li><strong>Correo electrónico de contacto:</strong> atencion@oasix.com.mx</li>
                    <li><strong>Sitio web y plataformas asociadas:</strong> los dominios, micrositios, portales o herramientas digitales utilizadas para la promoción y contratación de Servicios.</li>
                  </ul>
                  <p>OASIX se dedica a la conceptualización, organización y gestión de experiencias gastronómicas, culturales, turísticas, de entretenimiento y de activación de marca. Al contratar cualquier servicio, realizar una solicitud de reservación o efectuar un pago, el Usuario acepta expresamente las presentes Condiciones Generales.</p>

                  <h2>2. Objeto y alcance de los servicios</h2>
                  <p><strong>2.1.</strong> Los Servicios ofrecidos por OASIX incluyen, sin limitarse a:</p>
                  <ul>
                    <li><strong>Experiencias gastronómicas y culturales:</strong> tours culinarios, clases de cocina, catas, fiestas temáticas, recorridos guiados y actividades inmersivas en diferentes destinos de México.</li>
                    <li><strong>Activaciones y eventos de marca:</strong> diseño conceptual, producción, logística, ambientación y gestión de experiencias para empresas y clientes corporativos.</li>
                    <li><strong>Servicios turísticos complementarios:</strong> transporte opcional, coordinación logística, reservas de restaurantes, entradas a espectáculos y servicios de hospitalidad.</li>
                    <li><strong>Servicios adicionales relacionados con el Mundial 2026:</strong> reservaciones en restaurantes y bares, acceso a fan zones (Básica, Gastronómica y VIP Experiencial), actividades temáticas y experiencias de hospitalidad.</li>
                  </ul>
                  <p><strong>2.2.</strong> Cada Servicio contará con una descripción detallada en la plataforma digital de OASIX o en la propuesta enviada al cliente, especificando: duración, lugar de encuentro, características, entregables, restricciones, disponibilidad y condiciones particulares.</p>
                  <p><strong>2.3.</strong> OASIX se reserva el derecho de modificar, sustituir o actualizar el catálogo de Servicios en cualquier momento, sin necesidad de aviso previo, garantizando siempre el cumplimiento de las contrataciones confirmadas.</p>
                  <p><strong>2.4.</strong> El Usuario reconoce que los Servicios podrán depender de proveedores externos, y que las políticas internas de dichos terceros (restaurantes, bares, recintos, transportistas, guías, artistas, etc.) serán aplicables y vinculantes.</p>

                  <h2>3. Proceso de contratación</h2>
                  <p><strong>3.1. Medios habilitados para contratar.</strong> La contratación de los Servicios ofrecidos por OASIX únicamente podrá realizarse a través de los siguientes canales oficiales:</p>
                  <ul>
                    <li>El sitio web y plataformas digitales propiedad de OASIX o gestionadas directamente por ésta.</li>
                    <li>Solicitudes enviadas por correo electrónico al contacto oficial de OASIX.</li>
                    <li>Otros canales expresamente autorizados por OASIX (por ejemplo, acuerdos corporativos, agentes acreditados, convenios con empresas o colaboradores externos).</li>
                  </ul>
                  <p>Queda expresamente prohibida la contratación de Servicios a través de intermediarios no autorizados, páginas web apócrifas, revendedores o canales no reconocidos por OASIX. En tales casos, OASIX no asumirá responsabilidad alguna frente al Usuario.</p>
                  <p><strong>3.2. Obligaciones del Usuario al contratar.</strong> El Usuario se compromete a proporcionar, en el momento de la contratación, información veraz, completa, actualizada y suficiente para la correcta gestión del Servicio. Esto incluye, sin limitarse a: Nombre(s) y apellidos completos; Datos de contacto (correo electrónico, número telefónico y, en su caso, WhatsApp); Fecha, horario y destino de interés; Número de participantes, especificando si son adultos, menores de edad o personas con necesidades especiales; Requerimientos adicionales (alimenticios, médicos, logísticos, accesibilidad, etc.); Datos fiscales en caso de requerir factura. El Usuario será responsable de cualquier error, omisión o falsedad en los datos proporcionados. OASIX no será responsable por cancelaciones, rechazos de reserva, imposibilidad de acceso a experiencias o cargos adicionales ocasionados por información incorrecta o incompleta.</p>
                  <p><strong>3.3. Condiciones para la validez de la contratación.</strong> Toda contratación de Servicios estará siempre sujeta al cumplimiento acumulativo de los siguientes elementos: Confirmación de disponibilidad del servicio, fecha, lugar o proveedor por parte de OASIX; Asignación de un número de reservación único e intransferible, que identificará la contratación; Pago íntegro o parcial del precio del Servicio, conforme a las condiciones particulares indicadas (ej. apartado no reembolsable, pago total anticipado, saldo pendiente a liquidar en fecha determinada). Sin estos tres elementos, la contratación se considerará incompleta y no generará obligaciones para OASIX.</p>
                  <p><strong>3.4. Proceso de validación.</strong> Una vez recibido el pago y confirmada la disponibilidad, OASIX enviará al correo electrónico proporcionado por el Usuario un documento de confirmación de reserva, en el que constará: Número de reservación; Detalles del servicio contratado (fecha, hora, punto de encuentro, características principales); Nombre del titular de la reserva y número de participantes; Condiciones particulares y restricciones aplicables. En caso de que no se emita dicha confirmación, el Usuario deberá considerarse como no contratado el Servicio, aun cuando hubiese realizado el pago. OASIX se compromete, en tal caso, a gestionar de inmediato la devolución correspondiente.</p>
                  <p><strong>3.5. Carácter personal de la contratación.</strong> Las contrataciones realizadas son personales e intransferibles, salvo autorización expresa de OASIX. Queda prohibida la cesión, reventa, comercialización o transmisión de reservas sin autorización.</p>
                  <p><strong>3.6. Prevención de fraudes.</strong> OASIX se reserva el derecho de rechazar o cancelar cualquier contratación en la que existan indicios de: Información falsa o incompleta proporcionada por el Usuario; Pagos no reconocidos, sospecha de fraude bancario, clonación de tarjetas o contracargos; Revendedores no autorizados o usos indebidos de la marca OASIX.</p>

                  <h2>4. Reservaciones</h2>
                  <p><strong>4.1. Solicitud de reservación.</strong> Para solicitar un Servicio, el Usuario deberá enviar una solicitud de reservación a través de los medios habilitados por OASIX, los cuales podrán incluir: Formularios disponibles en el sitio web oficial; Correos electrónicos dirigidos a las cuentas oficiales de OASIX.</p>
                  <p><strong>4.2. Carácter no vinculante de la solicitud.</strong> La solicitud de reservación no implica confirmación automática del Servicio. Dicha solicitud será considerada únicamente como una petición sujeta a validación de disponibilidad, condiciones particulares, capacidad de aforo y pago del anticipo o totalidad del precio según corresponda.</p>
                  <p><strong>4.3. Condiciones para la confirmación.</strong> La reservación se considerará válida, vinculante y confirmada únicamente cuando se cumplan de manera acumulativa las siguientes condiciones: El Usuario reciba de OASIX un número de reservación único, personal e intransferible; El pago requerido (total o parcial, según el caso) haya sido procesado y confirmado por los sistemas de pago autorizados; El Usuario haya recibido un correo electrónico de confirmación con los detalles de la experiencia. Hasta que no concurran estos tres requisitos, la contratación se considerará incompleta y OASIX no asumirá ninguna obligación frente al Usuario.</p>
                  <p><strong>4.4. Contenido de la confirmación.</strong> El documento de confirmación de la reservación contendrá, al menos, la siguiente información: Fecha y hora del Servicio; Lugar o punto de encuentro; Número de participantes incluidos en la reservación; Condiciones particulares aplicables al Servicio; Restricciones, recomendaciones y requisitos específicos (ejemplo: código de vestimenta, edad mínima, documentos de identificación, puntualidad); Instrucciones adicionales necesarias para el correcto disfrute del Servicio.</p>
                  <p><strong>4.5. Imposibilidad de confirmación.</strong> En caso de que, por cualquier motivo, un Servicio no pueda confirmarse en la fecha, horario o condiciones solicitadas, OASIX podrá: Ofrecer al Usuario alternativas razonables, incluyendo cambio de fecha, de horario, de proveedor o de experiencia similar; Reembolsar el importe pagado por el Usuario, conforme a la política de cancelaciones aplicable. La aceptación de las alternativas será siempre a discreción del Usuario. En caso de rechazo, únicamente procederá el reembolso conforme a los términos aquí establecidos.</p>
                  <p><strong>4.6. Disponibilidad y políticas de proveedores.</strong> Todas las reservaciones estarán sujetas a la disponibilidad real del Servicio y a las políticas internas de cada establecimiento, proveedor, restaurante, bar, guía, transportista o artista involucrado. Dichas políticas podrán incluir, entre otros: Horarios de operación; Capacidad máxima de aforo; Restricciones de edad, salud, seguridad o accesibilidad; Normas de vestimenta o conducta; Reglas de consumo y permanencia en el recinto. El Usuario acepta que estas políticas de proveedores son vinculantes y forman parte integral de su contratación.</p>
                  <p><strong>4.7. Carácter personal e intransferible de la reservación.</strong> Cada reservación emitida es personal, nominativa e intransferible. Cualquier cesión, reventa o modificación no autorizada expresamente por OASIX carecerá de validez y podrá implicar la cancelación de la misma sin derecho a reembolso.</p>
                  <p><strong>4.8. Obligación de puntualidad.</strong> El Usuario deberá presentarse en el lugar y hora señalados en la confirmación de reservación. La falta de puntualidad podrá implicar la pérdida total del Servicio sin derecho a reembolso ni reprogramación.</p>

                  <h2>5. Servicios adicionales – Mundial 2026</h2>
                  <p><strong>5.1. Gestión de reservaciones en restaurantes y bares.</strong> Durante el periodo comprendido del 11 de junio al 19 de julio de 2026 (Copa Mundial de la FIFA 2026), OASIX ofrecerá al Usuario la posibilidad de gestionar reservaciones en restaurantes y bares reconocidos de la Ciudad de México, con el fin de que puedan disfrutar de la transmisión en vivo de los partidos en un ambiente controlado, temático y acompañado de servicios de hospitalidad. Las reservaciones estarán sujetas a la disponibilidad de cada establecimiento, a sus políticas internas y a los términos y condiciones específicos de cada recinto, que el Usuario acepta en el momento de la contratación.</p>
                  <p><strong>5.2. Consumo de alimentos y bebidas.</strong> El consumo de alimentos, bebidas y otros servicios adicionales (propinas, extras, pedidos especiales) no está incluido en la reservación inicial, salvo que expresamente se indique lo contrario en la descripción del paquete contratado. El pago de consumos adicionales será responsabilidad directa del Usuario frente al establecimiento. El incumplimiento de estas obligaciones podrá derivar en la cancelación del acceso o en cargos adicionales que serán responsabilidad exclusiva del Usuario.</p>
                  <p><strong>5.3. Modalidades de Fan Zone.</strong> OASIX pondrá a disposición del Usuario accesos a Fan Zones temáticas, ofrecidas en tres modalidades:</p>
                  <ul>
                    <li><strong>Fan Zone Básica:</strong> acceso a pantallas gigantes de transmisión en vivo, zonas de asientos o puffs, decoración futbolera temática, mini canchas para actividades recreativas (ej. penales o retas rápidas 3v3) y photobooth con accesorios mundialistas.</li>
                    <li><strong>Fan Zone Gastronómica:</strong> incluye todo lo señalado en la modalidad Básica, más áreas de food trucks y barras de snacks con gastronomía mexicana e internacional, coctelería temática inspirada en países participantes y maridaje con cervezas artesanales, tequilas o mezcales.</li>
                    <li><strong>Fan Zone VIP Experiencial:</strong> incluye lo anterior, más acceso a una zona lounge premium con mobiliario exclusivo, servicio personalizado de meseros, meet & greet con exfutbolistas o comentaristas deportivos (sujeto a disponibilidad y presupuesto), así como DJ o música en vivo antes y después de los partidos.</li>
                  </ul>
                  <p>El contenido exacto de cada Fan Zone podrá variar en función de los acuerdos con proveedores, disponibilidad de artistas y condiciones logísticas de cada evento.</p>
                  <p><strong>5.4. Condiciones generales aplicables a las experiencias.</strong> Las experiencias vinculadas al Mundial 2026 estarán sujetas, sin limitarse, a los siguientes factores: Disponibilidad de espacios y aforo máximo, en cumplimiento con las disposiciones legales y de protección civil vigentes en cada momento; Disponibilidad de artistas invitados, comentaristas o proveedores, quienes podrán ser sustituidos, modificados o cancelados por causas ajenas a OASIX; Cambios de horarios oficiales de partidos y transmisiones, derivados de la programación deportiva global; Restricciones de seguridad o sanitarias que pudieran imponer autoridades locales, recintos o proveedores.</p>
                  <p><strong>5.5. Exclusión de responsabilidad.</strong> OASIX no será responsable frente al Usuario por: Modificaciones, retrasos o cancelaciones en la programación oficial de los partidos de la Copa Mundial 2026; Decisiones operativas adoptadas por los establecimientos aliados (cambios de mesa, limitaciones de consumo, restricciones de acceso, normas de conducta, etc.); Causas de fuerza mayor o caso fortuito, incluyendo, sin limitarse, a condiciones climáticas, fallos en transmisiones satelitales, disposiciones gubernamentales o sanitarias.</p>
                  <p><strong>5.6. Confirmación y pago de reservación.</strong> El Usuario reconoce que su acceso a las experiencias adicionales del Mundial 2026 quedará confirmado únicamente cuando: Reciba un número de reservación emitido por OASIX; Realice el pago de la reservación, ingresando dicho número y el monto indicado en la plataforma de pago habilitada; Obtenga un correo electrónico de confirmación que detalle fecha, lugar, modalidad de Fan Zone o restaurante asignado y número de participantes. El pago de la reservación podrá ser no reembolsable, conforme a las políticas de cada proveedor y a lo establecido en el apartado de cancelaciones y reembolsos.</p>

                  <h2>6. Pagos</h2>
                  <p><strong>6.1. Moneda e impuestos aplicables.</strong> Todos los precios publicados estarán expresados en pesos mexicanos (MXN), salvo indicación en contrario, e incluirán los impuestos aplicables conforme a la legislación fiscal vigente. En caso de cotizar en otra moneda, el cargo final se realizará en pesos mexicanos al tipo de cambio aplicable en la fecha de liquidación. El Usuario será responsable de cualquier comisión bancaria, cargo por tipo de cambio o tarifa adicional impuesta por su institución financiera.</p>
                  <p><strong>6.2. Métodos de pago autorizados.</strong> El Usuario podrá realizar los pagos exclusivamente mediante los métodos electrónicos autorizados en el portal de OASIX, que podrán incluir: Tarjetas de crédito y débito; Plataformas de pago electrónico o billeteras digitales que se encuentren expresamente habilitadas en el sistema de OASIX. Queda prohibido efectuar pagos a cuentas o enlaces no oficiales. OASIX no será responsable por pagos realizados a terceros no autorizados.</p>
                  <p><strong>6.3. Confirmación del pago y validación de reservación.</strong> Para confirmar su lugar en un Servicio, el Usuario deberá: Ingresar su número de reservación en la plataforma de pago habilitada; Liquidar el monto correspondiente conforme a lo indicado en la confirmación de reservación; Esperar la validación electrónica de la operación. El Servicio se considerará asegurado únicamente cuando el pago haya sido efectivamente acreditado y confirmado por OASIX.</p>
                  <p><strong>6.4. Comprobantes y facturación.</strong> Una vez procesado el pago, el Usuario recibirá en el correo registrado: Confirmación electrónica de la reserva; Comprobante de pago emitido por la pasarela correspondiente. En caso de requerir factura fiscal (CFDI), el Usuario deberá solicitarla al momento de la contratación, proporcionando datos fiscales correctos y completos. OASIX no será responsable por errores en la facturación derivados de datos incorrectos proporcionados por el Usuario ni podrá reexpedir comprobantes fuera de los plazos legales.</p>
                  <p><strong>6.5. Rechazos, contracargos y falta de acreditación.</strong> En los siguientes supuestos, la reservación quedará automáticamente cancelada sin responsabilidad para OASIX: Rechazo de la transacción por parte de la institución emisora del medio de pago; Falta de acreditación del pago dentro de los plazos señalados; Detección de operaciones sospechosas de fraude, clonación de tarjetas, suplantación de identidad o contracargos iniciados por el Usuario. En caso de contracargos, OASIX se reserva el derecho de reclamar judicial o extrajudicialmente los importes correspondientes, así como los gastos administrativos y legales derivados.</p>
                  <p><strong>6.6. Pagos parciales, anticipos y no reembolsabilidad.</strong> Dependiendo del Servicio, podrá requerirse: Pago total anticipado: para confirmar la reserva; Pago parcial o anticipo no reembolsable: como apartado para asegurar disponibilidad; Saldo pendiente: a liquidarse en la fecha y forma indicada en la confirmación. En caso de que el Usuario no liquide el saldo en los tiempos previstos, la reservación podrá ser cancelada, perdiendo el anticipo no reembolsable.</p>
                  <p><strong>6.7. Seguridad en transacciones.</strong> Todas las operaciones realizadas a través de los portales de pago de OASIX estarán encriptadas y protegidas por certificados de seguridad SSL y sistemas antifraude. Sin embargo, el Usuario reconoce que ninguna transmisión electrónica está totalmente libre de riesgos y exime a OASIX de responsabilidad por vulneraciones derivadas de actos de terceros ajenos a su control.</p>

                  <h2>7. Cancelaciones, modificaciones y reembolsos</h2>
                  <p><strong>7.1. Solicitud de cancelación o modificación.</strong> El Usuario podrá solicitar la modificación o cancelación de su reservación enviando un correo electrónico a la dirección oficial de contacto de OASIX (atencion@oasix.com.mx), indicando de forma clara: Número de reservación; Nombre completo del titular de la reserva; Servicio contratado; Fecha prevista del Servicio; Motivo de la cancelación o modificación solicitada.</p>
                  <p><strong>7.2. Condiciones de aceptación.</strong> Las solicitudes estarán sujetas a las siguientes condiciones: Antelación con que se realicen: dependiendo de la naturaleza del Servicio, el plazo mínimo de preaviso podrá ser de 7 días naturales (para experiencias generales), 3 días naturales (para experiencias gastronómicas específicas) o 1 día natural (para experiencias de consumo inmediato o bajo aforo limitado); Políticas particulares del proveedor o establecimiento: cada restaurante, bar, recinto o proveedor podrá aplicar sus propias reglas en materia de cancelaciones, modificaciones y reembolsos; Disponibilidad en la nueva fecha solicitada: la reprogramación quedará siempre condicionada a la capacidad del proveedor para aceptar cambios. El Usuario reconoce que en algunos casos las solicitudes realizadas fuera de los plazos establecidos no podrán ser atendidas, lo que implicará la pérdida total del importe abonado.</p>
                  <p><strong>7.3. Gestión por parte de OASIX.</strong> En los casos en que proceda, OASIX actuará como intermediario para gestionar ante el proveedor la modificación, reprogramación o, en su caso, el reembolso parcial o total del servicio contratado. La aceptación final de la cancelación o modificación dependerá siempre de las políticas del proveedor. OASIX se compromete a comunicar al Usuario, en un plazo razonable, la resolución adoptada por el proveedor.</p>
                  <p><strong>7.4. Servicios no reembolsables.</strong> Existen servicios, anticipos o apartados que podrán ser no reembolsables, lo cual será informado al Usuario antes de la confirmación de la contratación. Ejemplos: Reservaciones en fechas de alta demanda (ej. partidos del Mundial 2026, eventos especiales, festividades nacionales); Servicios con cupo limitado o con pago de artistas, guías o recintos por anticipado; Anticipos destinados a asegurar disponibilidad. En estos casos, la cancelación por parte del Usuario no dará lugar a devolución alguna, independientemente de la causa invocada.</p>
                  <p><strong>7.5. Forma de reembolso.</strong> Cuando proceda, los reembolsos se realizarán utilizando el mismo método de pago empleado por el Usuario. Si por razones técnicas no fuera posible, OASIX podrá efectuar la devolución mediante transferencia bancaria a una cuenta a nombre del titular original de la reservación. El monto reembolsado corresponderá únicamente al importe efectivamente pagado por el Usuario a OASIX, sin incluir gastos financieros, comisiones bancarias ni costos adicionales asumidos por el Usuario.</p>
                  <p><strong>7.6. Plazos de acreditación.</strong> Los tiempos de acreditación del reembolso dependerán de los plazos establecidos por las instituciones financieras, pudiendo extenderse entre 5 y 20 días hábiles contados a partir de la confirmación de procedencia del reembolso.</p>
                  <p><strong>7.7. Limitación de responsabilidad.</strong> El Usuario reconoce y acepta que: OASIX no podrá garantizar devoluciones cuando los proveedores determinen que no procede el reembolso; OASIX no será responsable de los retrasos imputables a instituciones financieras o pasarelas de pago; En ningún caso se devolverán importes correspondientes a consumos adicionales, propinas, gastos de transporte u otros servicios no contratados directamente con OASIX.</p>

                  <h2>8. Obligaciones del Usuario</h2>
                  <p>El Usuario, al contratar y utilizar los Servicios de OASIX, acepta de manera expresa las siguientes obligaciones:</p>
                  <p><strong>8.1. Veracidad y exactitud de la información.</strong> Proporcionar datos veraces, completos, exactos y actualizados en todo momento. Notificar de inmediato cualquier error u omisión detectado en los datos enviados a OASIX. Reconocer que cualquier inexactitud, falsedad u omisión será responsabilidad exclusiva del Usuario y podrá derivar en la cancelación del Servicio sin derecho a reembolso.</p>
                  <p><strong>8.2. Cumplimiento de requisitos específicos.</strong> Acreditar, cuando aplique, los requisitos de edad mínima, documentación (INE, pasaporte, visa, comprobantes médicos, certificados de vacunación, etc.) o condiciones de seguridad exigidas para el Servicio contratado. Seguir las instrucciones, restricciones y recomendaciones indicadas por OASIX o por los proveedores durante la experiencia. En caso de menores de edad, garantizar que estos participen bajo la supervisión directa de un adulto responsable.</p>
                  <p><strong>8.3. Respeto de políticas y normas de convivencia.</strong> Respetar las políticas de conducta, higiene, vestimenta, seguridad, convivencia y puntualidad establecidas por OASIX, por los proveedores, restaurantes, bares, venues o recintos contratados. Abstenerse de conductas inapropiadas, agresivas, discriminatorias o que alteren el orden y la seguridad del evento. Cumplir con las normas sanitarias, de protección civil y de seguridad dictadas por autoridades o proveedores. El incumplimiento de estas políticas facultará a OASIX o al proveedor a negar el acceso, retirar al Usuario del evento o cancelar la prestación del Servicio, sin obligación de reembolso.</p>
                  <p><strong>8.4. Responsabilidad sobre gastos adicionales.</strong> Asumir íntegramente los costos de transporte hacia y desde el punto de encuentro, salvo que el mismo esté expresamente incluido en el paquete. Cubrir propinas, consumos adicionales, bebidas, alimentos, souvenirs u otros gastos no contemplados en la contratación inicial. Reconocer que estos gastos no son responsabilidad de OASIX.</p>
                  <p><strong>8.5. Prohibición de reventa o cesión no autorizada.</strong> No revender, transferir, ceder ni comercializar las reservaciones sin autorización previa y expresa de OASIX. Reconocer que cualquier intento de reventa o cesión no autorizada invalidará la reservación de forma automática, sin derecho a reembolso.</p>
                  <p><strong>8.6. Consumo responsable de alcohol y sustancias.</strong> En experiencias donde se incluya consumo de bebidas alcohólicas (ej. catas, fan zones, tours gastronómicos), hacerlo de manera responsable y conforme a las leyes locales. Queda prohibido el consumo de drogas, estupefacientes o sustancias ilegales en todos los Servicios gestionados por OASIX. El incumplimiento facultará a OASIX o al proveedor a negar el acceso o retirar al Usuario del evento sin derecho a reembolso.</p>
                  <p><strong>8.7. Puntualidad y asistencia.</strong> Presentarse puntualmente en el lugar, fecha y hora indicados en la confirmación de reservación. Reconocer que los Servicios tienen un tiempo de inicio fijo y que la impuntualidad podrá implicar la pérdida parcial o total de la experiencia sin derecho a reembolso.</p>
                  <p><strong>8.8. Daños y responsabilidad personal.</strong> Cuidar y hacer uso adecuado de las instalaciones, mobiliario, equipos, transportes, materiales y objetos puestos a disposición durante la experiencia. Responder económicamente por los daños ocasionados de manera dolosa o negligente a terceros, instalaciones, mobiliario o equipo utilizado en la experiencia.</p>
                  <p><strong>8.9. Aceptación de consecuencias por incumplimiento.</strong> El incumplimiento por parte del Usuario de cualquiera de las obligaciones aquí previstas facultará a OASIX y/o a los proveedores a: Cancelar el Servicio contratado sin derecho a reembolso; Negar el acceso al evento o experiencia; Solicitar la reparación de daños y perjuicios ocasionados; Ejercer las acciones legales correspondientes para proteger sus derechos.</p>

                  <h2>9. Limitación de responsabilidad</h2>
                  <p><strong>9.1. Naturaleza de la intervención de OASIX.</strong> El Usuario reconoce y acepta que OASIX actúa como gestor, organizador y en muchos casos como intermediario entre el Usuario y proveedores externos de servicios (restaurantes, bares, venues, guías, transportistas, artistas, recintos turísticos, entre otros). Por tanto, la correcta ejecución de ciertos servicios depende directamente de dichos proveedores, cuyas políticas internas resultan vinculantes para el Usuario.</p>
                  <p><strong>9.2. Exclusiones de responsabilidad.</strong> OASIX no será responsable, en ningún caso, por: Cancelaciones, retrasos, fallas o deficiencias imputables a proveedores externos contratados para la ejecución parcial o total del Servicio; Condiciones climáticas adversas, fenómenos naturales, eventos de fuerza mayor o caso fortuito que afecten la ejecución del Servicio; Situaciones sanitarias, restricciones gubernamentales o medidas de seguridad pública que impidan o limiten el desarrollo del Servicio; Pérdida, robo o daño de pertenencias personales del Usuario antes, durante o después del Servicio; Accidentes, lesiones, enfermedades o daños ocasionados por la negligencia, imprudencia, incumplimiento de instrucciones o estado de salud del Usuario; Daños indirectos, pérdidas de oportunidad, expectativas de negocio, ingresos futuros, gastos colaterales o cualquier forma de lucro cesante.</p>
                  <p><strong>9.3. Riesgos asumidos por el Usuario.</strong> El Usuario reconoce y acepta que la participación en experiencias gastronómicas, culturales, de entretenimiento o eventos deportivos conlleva ciertos riesgos inherentes, entre los que se incluyen, de manera enunciativa mas no limitativa: Riesgos alimenticios (alergias, intolerancias, intoxicaciones); Riesgos físicos (caídas, lesiones menores o mayores en actividades recreativas, deportivas o de transporte); Riesgos asociados al consumo de bebidas alcohólicas; Riesgos de interacción con multitudes o eventos masivos. El Usuario declara ser consciente de estos riesgos, y asume plena responsabilidad sobre su participación en las experiencias contratadas.</p>
                  <p><strong>9.4. Limitación cuantitativa de responsabilidad.</strong> En cualquier caso, la responsabilidad máxima de OASIX frente al Usuario se limitará estrictamente al monto efectivamente pagado por el Usuario por el Servicio específico contratado que haya dado origen a la reclamación. En ningún caso procederán indemnizaciones por montos superiores, daños punitivos ni compensaciones adicionales. Si la reclamación involucrara a un tercero proveedor, la eventual responsabilidad quedará sujeta a las políticas y limitaciones legales de dicho proveedor.</p>
                  <p><strong>9.5. Exoneración en caso de incumplimiento del Usuario.</strong> OASIX no será responsable por el incumplimiento, total o parcial, del Servicio cuando éste derive de: La falta de puntualidad del Usuario; El incumplimiento de requisitos de acceso (documentación, edad mínima, vestimenta); La omisión de restricciones médicas, sanitarias o de seguridad notificadas previamente; Conductas inadecuadas, negligentes o ilícitas por parte del Usuario o sus acompañantes.</p>
                  <p><strong>9.6. Indemnidad.</strong> El Usuario se obliga a sacar en paz y a salvo a OASIX de cualquier reclamación, demanda, procedimiento o acción judicial interpuesta por terceros derivada de actos u omisiones del propio Usuario durante la ejecución del Servicio.</p>

                  <h2>10. Propiedad intelectual</h2>
                  <p><strong>10.1. Titularidad de derechos.</strong> Todos los contenidos disponibles en los sitios, plataformas y materiales promocionales de OASIX —incluyendo, sin limitación, textos, descripciones de servicios, material gráfico, logotipos, marcas registradas, nombres comerciales, fotografías, imágenes, audios, videos, diseños, iconos, interfaces, códigos fuente y cualquier otro elemento protegido por derechos de propiedad intelectual o industrial— son propiedad exclusiva de GREATDEN, S.A. DE C.V. o de terceros licenciantes que han autorizado su uso.</p>
                  <p><strong>10.2. Protección legal.</strong> Dichos contenidos se encuentran protegidos por la legislación nacional e internacional en materia de derechos de autor, propiedad industrial y propiedad intelectual, incluyendo, de manera enunciativa mas no limitativa: La Ley Federal del Derecho de Autor de México; La Ley de la Propiedad Industrial de México; Tratados internacionales suscritos por los Estados Unidos Mexicanos, tales como el Convenio de Berna, ADPIC (TRIPS) y tratados de la OMPI.</p>
                  <p><strong>10.3. Licencia de uso limitada.</strong> El acceso al sitio web y a los materiales de OASIX no concede al Usuario derecho alguno de explotación sobre los contenidos, salvo una licencia de uso personal, limitada, no exclusiva, revocable y no transferible, cuyo único fin es permitir la correcta contratación y disfrute de los servicios.</p>
                  <p><strong>10.4. Usos prohibidos.</strong> Queda estrictamente prohibido, sin autorización previa y por escrito de OASIX: Reproducir, copiar, distribuir, comunicar públicamente, transformar, modificar, traducir, adaptar, descompilar, extraer o utilizar con fines comerciales o promocionales los contenidos protegidos; Utilizar logotipos, nombres comerciales, marcas o signos distintivos de OASIX para fines publicitarios, comerciales o de asociación sin consentimiento expreso; Generar obras derivadas, sitios espejo, reventa de contenidos, scraping o extracción de bases de datos pertenecientes a OASIX.</p>
                  <p><strong>10.5. Contenidos de terceros y licencias.</strong> En caso de que algunos contenidos, fotografías, imágenes, videos o materiales pertenecieran a terceros y se utilicen bajo licencias, cesiones o autorizaciones, dichos derechos corresponderán a sus respectivos titulares. El Usuario se obliga a respetar íntegramente tales derechos y a no realizar actos que vulneren su protección legal.</p>
                  <p><strong>10.6. Infracciones.</strong> Cualquier uso no autorizado de los contenidos propiedad de OASIX o de sus licenciantes constituirá una infracción a los derechos de propiedad intelectual e industrial, pudiendo dar lugar a: La exigencia de responsabilidad civil por daños y perjuicios; El ejercicio de acciones legales civiles, administrativas y/o penales conforme a la legislación aplicable; La suspensión inmediata de los accesos o servicios contratados, sin obligación de reembolso.</p>
                  <p><strong>10.7. Colaboraciones y cesión de contenidos.</strong> En caso de que un Usuario participe en actividades de co-creación de contenido (ejemplo: fotografías, testimonios, grabaciones en tours o fan zones), éste concede a OASIX, de forma gratuita, una licencia no exclusiva, transferible, sublicenciable, mundial y por tiempo indefinido para usar, reproducir, comunicar públicamente, distribuir y transformar dicho contenido, única y exclusivamente con fines promocionales, comerciales o publicitarios relacionados con los servicios de OASIX.</p>

                  <h2>12. Legislación aplicable y jurisdicción</h2>
                  <p><strong>12.1.</strong> Las presentes Condiciones Generales se regirán por las leyes de los Estados Unidos Mexicanos.</p>
                  <p><strong>12.2.</strong> Para cualquier controversia derivada de la interpretación o ejecución de estas Condiciones, las partes se someten a los tribunales competentes de la Ciudad de México, renunciando expresamente a cualquier otro fuero que pudiera corresponderles.</p>

                  <h2>13. Disposiciones finales</h2>
                  <p><strong>13.1. Facultad de modificación.</strong> OASIX se reserva el derecho de modificar, actualizar o complementar en cualquier momento las presentes Condiciones Generales, ya sea por cambios normativos, por ajustes en sus operaciones internas o por mejoras en la prestación de sus servicios. La versión actualizada será publicada en el sitio web oficial de OASIX y sustituirá a la anterior a partir de su fecha de publicación.</p>
                  <p><strong>13.2. Responsabilidad del Usuario.</strong> Será responsabilidad exclusiva del Usuario revisar periódicamente las Condiciones Generales vigentes antes de contratar o utilizar cualquier servicio. La contratación posterior a la publicación de modificaciones constituirá aceptación plena, expresa e incondicional de dichas modificaciones.</p>
                  <p><strong>13.3. Carácter vinculante.</strong> El Usuario reconoce que estas Condiciones Generales, junto con las condiciones particulares de cada Servicio, constituyen el acuerdo completo, único y vinculante entre las partes, sustituyendo cualquier comunicación, propuesta o entendimiento previo, ya sea verbal o escrito.</p>
                  <p><strong>13.4. Divisibilidad.</strong> Si alguna de las disposiciones de estas Condiciones fuese declarada nula, ilegal o inaplicable por autoridad competente, dicha nulidad o inaplicabilidad no afectará la validez y exigibilidad del resto de las cláusulas, las cuales permanecerán vigentes y aplicables en todos sus términos.</p>
                  <p><strong>13.5. No renuncia de derechos.</strong> La falta o demora de OASIX en ejercer cualquier derecho o facultad derivado de estas Condiciones no constituirá una renuncia al mismo, ni impedirá su ejercicio posterior.</p>
                  <p><strong>13.6. Idioma.</strong> En caso de discrepancia entre la versión en español y una eventual traducción a otro idioma de estas Condiciones, prevalecerá siempre la versión en español.</p>
                  <p><strong>13.7. Vigencia.</strong> Estas Condiciones Generales estarán vigentes desde su fecha de publicación en el sitio web oficial de OASIX y permanecerán aplicables hasta que sean sustituidas por una nueva versión.</p>
                </>
              ) : (
                <>
                  <h2>1. Company Identity</h2>
                  <p><strong>1.1.</strong> This document establishes the General Terms and Conditions of Contracting (hereinafter, the “General Conditions”) that govern the legal relationship between the users (hereinafter, the “User” or the “Users”) and GREATDEN, S.A. DE C.V. (hereinafter, “OASIX”), a company incorporated under Mexican laws.</p>
                  <p><strong>1.2. Identification data:</strong></p>
                  <ul>
                    <li><strong>Corporate name:</strong> GREATDEN, S.A. DE C.V.</li>
                    <li><strong>Address:</strong> Av. Río Consulado Cto Interior 516, Oficina 102, Col. Tlatilco, Alcaldía Azcapotzalco, C.P. 02860, Mexico City.</li>
                    <li><strong>Contact email:</strong> atencion@oasix.com.mx</li>
                    <li><strong>Website and associated platforms:</strong> the domains, microsites, portals, or digital tools used for the promotion and contracting of Services.</li>
                  </ul>
                  <p>OASIX is dedicated to the conceptualization, organization, and management of gastronomic, cultural, tourism, entertainment, and brand activation experiences. By contracting any service, submitting a reservation request, or making a payment, the User expressly accepts these General Conditions.</p>

                  <h2>2. Object and scope of services</h2>
                  <p><strong>2.1.</strong> The Services offered by OASIX include, but are not limited to:</p>
                  <ul>
                    <li><strong>Gastronomic and cultural experiences:</strong> culinary tours, cooking classes, tastings, themed parties, guided tours, and immersive activities in different destinations in Mexico.</li>
                    <li><strong>Brand activations and events:</strong> conceptual design, production, logistics, ambiance, and experience management for companies and corporate clients.</li>
                    <li><strong>Complementary tourism services:</strong> optional transportation, logistical coordination, restaurant reservations, show tickets, and hospitality services.</li>
                    <li><strong>Additional services related to the 2026 World Cup:</strong> reservations in restaurants and bars, access to fan zones (Basic, Gastronomic, and Experiential VIP), themed activities, and hospitality experiences.</li>
                  </ul>
                  <p><strong>2.2.</strong> Each Service will have a detailed description on the OASIX digital platform or in the proposal sent to the client, specifying: duration, meeting place, features, deliverables, restrictions, availability, and specific conditions.</p>
                  <p><strong>2.3.</strong> OASIX reserves the right to modify, substitute, or update the Services catalog at any time, without prior notice, always ensuring compliance with confirmed contracts.</p>
                  <p><strong>2.4.</strong> The User acknowledges that the Services may depend on external providers, and that the internal policies of said third parties (restaurants, bars, venues, transporters, guides, artists, etc.) will be applicable and binding.</p>

                  <h2>3. Contracting process</h2>
                  <p><strong>3.1. Authorized means to contract.</strong> The contracting of the Services offered by OASIX may only be done through the following official channels:</p>
                  <ul>
                    <li>The website and digital platforms owned by OASIX or managed directly by it.</li>
                    <li>Requests sent by email to the official OASIX contact.</li>
                    <li>Other channels expressly authorized by OASIX (e.g., corporate agreements, accredited agents, agreements with companies or external collaborators).</li>
                  </ul>
                  <p>Contracting Services through unauthorized intermediaries, fake websites, resellers, or unrecognized channels is expressly prohibited. In such cases, OASIX will not assume any responsibility towards the User.</p>
                  <p><strong>3.2. User obligations when contracting.</strong> The User commits to providing, at the time of contracting, truthful, complete, updated, and sufficient information for the correct management of the Service. This includes, but is not limited to: Full name(s) and surname(s); Contact details (email, phone number, and WhatsApp, if applicable); Date, time, and destination of interest; Number of participants, specifying if they are adults, minors, or persons with special needs; Additional requirements (dietary, medical, logistical, accessibility, etc.); Tax data in case an invoice is required. The User will be responsible for any error, omission, or falsehood in the provided data. OASIX will not be responsible for cancellations, reservation rejections, inability to access experiences, or additional charges caused by incorrect or incomplete information.</p>
                  <p><strong>3.3. Conditions for contracting validity.</strong> All Service contracting will always be subject to the cumulative fulfillment of the following elements: Confirmation of availability of the service, date, location, or provider by OASIX; Assignment of a unique and non-transferable reservation number, which will identify the contract; Full or partial payment of the Service price, according to the specified conditions (e.g., non-refundable deposit, full advance payment, pending balance to be settled on a specific date). Without these three elements, the contracting will be considered incomplete and will not generate obligations for OASIX.</p>
                  <p><strong>3.4. Validation process.</strong> Once the payment is received and availability is confirmed, OASIX will send a reservation confirmation document to the email provided by the User, containing: Reservation number; Details of the contracted service (date, time, meeting point, main features); Name of the reservation holder and number of participants; Specific conditions and applicable restrictions. In case such confirmation is not issued, the User must consider the Service as not contracted, even if the payment was made. OASIX commits, in such case, to immediately process the corresponding refund.</p>
                  <p><strong>3.5. Personal nature of the contracting.</strong> The contracts made are personal and non-transferable, unless expressly authorized by OASIX. The assignment, resale, marketing, or transmission of reservations without authorization is prohibited.</p>
                  <p><strong>3.6. Fraud prevention.</strong> OASIX reserves the right to reject or cancel any contract where there are indications of: False or incomplete information provided by the User; Unrecognized payments, suspicion of bank fraud, card cloning, or chargebacks; Unauthorized resellers or misuse of the OASIX brand.</p>

                  <h2>4. Reservations</h2>
                  <p><strong>4.1. Reservation request.</strong> To request a Service, the User must send a reservation request through the channels enabled by OASIX, which may include: Forms available on the official website; Emails directed to the official OASIX accounts.</p>
                  <p><strong>4.2. Non-binding nature of the request.</strong> The reservation request does not imply automatic confirmation of the Service. Said request will be considered solely as a petition subject to validation of availability, specific conditions, capacity limits, and payment of the deposit or total price as appropriate.</p>
                  <p><strong>4.3. Conditions for confirmation.</strong> The reservation will be considered valid, binding, and confirmed only when the following conditions are cumulatively met: The User receives a unique, personal, and non-transferable reservation number from OASIX; The required payment (total or partial, as the case may be) has been processed and confirmed by the authorized payment systems; The User has received a confirmation email with the experience details. Until these three requirements are met, the contracting will be considered incomplete, and OASIX will not assume any obligation towards the User.</p>
                  <p><strong>4.4. Content of the confirmation.</strong> The reservation confirmation document will contain, at least, the following information: Date and time of the Service; Place or meeting point; Number of participants included in the reservation; Specific conditions applicable to the Service; Restrictions, recommendations, and specific requirements (e.g., dress code, minimum age, identification documents, punctuality); Additional instructions necessary for the proper enjoyment of the Service.</p>
                  <p><strong>4.5. Impossibility of confirmation.</strong> If, for any reason, a Service cannot be confirmed on the requested date, time, or conditions, OASIX may: Offer the User reasonable alternatives, including a change of date, time, provider, or a similar experience; Refund the amount paid by the User, in accordance with the applicable cancellation policy. The acceptance of the alternatives will always be at the User's discretion. In case of rejection, only the refund will proceed in accordance with the terms established herein.</p>
                  <p><strong>4.6. Availability and provider policies.</strong> All reservations will be subject to the real availability of the Service and the internal policies of each establishment, provider, restaurant, bar, guide, transporter, or artist involved. Such policies may include, among others: Operating hours; Maximum capacity limits; Age, health, safety, or accessibility restrictions; Dress code or conduct norms; Rules for consumption and stay in the venue. The User accepts that these provider policies are binding and form an integral part of their contract.</p>
                  <p><strong>4.7. Personal and non-transferable nature of the reservation.</strong> Each issued reservation is personal, nominative, and non-transferable. Any unauthorized assignment, resale, or modification expressly by OASIX will be invalid and may result in its cancellation without the right to a refund.</p>
                  <p><strong>4.8. Punctuality obligation.</strong> The User must appear at the place and time indicated in the reservation confirmation. Lack of punctuality may result in the total loss of the Service without the right to a refund or rescheduling.</p>

                  <h2>5. Additional services – 2026 World Cup</h2>
                  <p><strong>5.1. Management of reservations in restaurants and bars.</strong> During the period from June 11 to July 19, 2026 (FIFA World Cup 2026), OASIX will offer the User the possibility of managing reservations in recognized restaurants and bars in Mexico City, so that they can enjoy the live broadcast of the matches in a controlled, themed environment accompanied by hospitality services. Reservations will be subject to the availability of each establishment, their internal policies, and the specific terms and conditions of each venue, which the User accepts at the time of contracting.</p>
                  <p><strong>5.2. Food and beverage consumption.</strong> The consumption of food, beverages, and other additional services (tips, extras, special requests) is not included in the initial reservation, unless expressly stated otherwise in the description of the contracted package. The payment of additional consumptions will be the direct responsibility of the User towards the establishment. Failure to comply with these obligations may result in access cancellation or additional charges that will be the exclusive responsibility of the User.</p>
                  <p><strong>5.3. Fan Zone Modalities.</strong> OASIX will make available to the User access to themed Fan Zones, offered in three modalities:</p>
                  <ul>
                    <li><strong>Basic Fan Zone:</strong> access to giant screens for live broadcasting, seating areas or bean bags, themed soccer decoration, mini courts for recreational activities (e.g., penalty kicks or quick 3v3 matches), and a photobooth with World Cup accessories.</li>
                    <li><strong>Gastronomic Fan Zone:</strong> includes everything mentioned in the Basic modality, plus food truck areas and snack bars with Mexican and international gastronomy, themed cocktails inspired by participating countries, and pairing with craft beers, tequilas, or mezcals.</li>
                    <li><strong>Experiential VIP Fan Zone:</strong> includes the above, plus access to a premium lounge area with exclusive furniture, personalized waiter service, meet & greet with former footballers or sports commentators (subject to availability and budget), as well as a DJ or live music before and after the matches.</li>
                  </ul>
                  <p>The exact content of each Fan Zone may vary depending on provider agreements, artist availability, and the logistical conditions of each event.</p>
                  <p><strong>5.4. General conditions applicable to the experiences.</strong> Experiences linked to the 2026 World Cup will be subject, without limitation, to the following factors: Space availability and maximum capacity, in compliance with current legal and civil protection provisions; Availability of guest artists, commentators, or providers, who may be substituted, modified, or canceled for reasons beyond OASIX's control; Changes in official match and broadcast schedules, derived from global sports programming; Security or health restrictions that local authorities, venues, or providers might impose.</p>
                  <p><strong>5.5. Exclusion of liability.</strong> OASIX will not be responsible to the User for: Modifications, delays, or cancellations in the official match schedule of the 2026 World Cup; Operational decisions adopted by partner establishments (table changes, consumption limitations, access restrictions, conduct rules, etc.); Force majeure or unforeseeable circumstances, including, without limitation, weather conditions, satellite transmission failures, government or health provisions.</p>
                  <p><strong>5.6. Confirmation and payment of reservation.</strong> The User acknowledges that their access to the additional experiences of the 2026 World Cup will only be confirmed when: They receive a reservation number issued by OASIX; They make the payment for the reservation, entering said number and the indicated amount in the enabled payment platform; They obtain a confirmation email detailing the date, location, Fan Zone modality or assigned restaurant, and number of participants. The reservation payment may be non-refundable, in accordance with each provider's policies and the cancellation and refund section.</p>

                  <h2>6. Payments</h2>
                  <p><strong>6.1. Currency and applicable taxes.</strong> All published prices will be expressed in Mexican pesos (MXN), unless otherwise indicated, and will include the applicable taxes in accordance with current tax legislation. If quoted in another currency, the final charge will be made in Mexican pesos at the exchange rate applicable on the settlement date. The User will be responsible for any bank commission, exchange rate charge, or additional fee imposed by their financial institution.</p>
                  <p><strong>6.2. Authorized payment methods.</strong> The User may make payments exclusively through the electronic methods authorized on the OASIX portal, which may include: Credit and debit cards; Electronic payment platforms or digital wallets expressly enabled in the OASIX system. It is prohibited to make payments to unofficial accounts or links. OASIX will not be responsible for payments made to unauthorized third parties.</p>
                  <p><strong>6.3. Payment confirmation and reservation validation.</strong> To confirm their place in a Service, the User must: Enter their reservation number on the enabled payment platform; Settle the corresponding amount as indicated in the reservation confirmation; Wait for the electronic validation of the operation. The Service will be considered secured only when the payment has been effectively credited and confirmed by OASIX.</p>
                  <p><strong>6.4. Receipts and billing.</strong> Once the payment is processed, the User will receive at the registered email: Electronic reservation confirmation; Payment receipt issued by the corresponding gateway. If a tax invoice (CFDI) is required, the User must request it at the time of contracting, providing correct and complete tax data. OASIX will not be responsible for billing errors derived from incorrect data provided by the User, nor will it be able to reissue receipts outside the legal deadlines.</p>
                  <p><strong>6.5. Rejections, chargebacks, and non-accreditation.</strong> In the following cases, the reservation will be automatically canceled without liability for OASIX: Transaction rejection by the issuing institution of the payment method; Failure to credit the payment within the indicated deadlines; Detection of suspicious operations of fraud, card cloning, identity theft, or chargebacks initiated by the User. In case of chargebacks, OASIX reserves the right to claim the corresponding amounts judicially or extrajudicially, as well as the derived administrative and legal expenses.</p>
                  <p><strong>6.6. Partial payments, deposits, and non-refundability.</strong> Depending on the Service, the following may be required: Full advance payment: to confirm the reservation; Partial payment or non-refundable deposit: to secure availability; Pending balance: to be settled on the date and manner indicated in the confirmation. In case the User does not settle the balance in the expected time, the reservation may be canceled, losing the non-refundable deposit.</p>
                  <p><strong>6.7. Security in transactions.</strong> All operations carried out through OASIX's payment portals will be encrypted and protected by SSL security certificates and anti-fraud systems. However, the User acknowledges that no electronic transmission is completely risk-free and exempts OASIX from liability for vulnerabilities derived from acts of third parties beyond its control.</p>

                  <h2>7. Cancellations, modifications, and refunds</h2>
                  <p><strong>7.1. Cancellation or modification request.</strong> The User may request the modification or cancellation of their reservation by sending an email to the official OASIX contact address (atencion@oasix.com.mx), clearly indicating: Reservation number; Full name of the reservation holder; Contracted service; Scheduled date of the Service; Reason for the requested cancellation or modification.</p>
                  <p><strong>7.2. Acceptance conditions.</strong> Requests will be subject to the following conditions: Notice period: depending on the nature of the Service, the minimum notice period may be 7 calendar days (for general experiences), 3 calendar days (for specific gastronomic experiences), or 1 calendar day (for immediate consumption experiences or limited capacity); Specific policies of the provider or establishment: each restaurant, bar, venue, or provider may apply its own rules regarding cancellations, modifications, and refunds; Availability on the newly requested date: rescheduling will always be conditioned on the provider's capacity to accept changes. The User acknowledges that in some cases requests made outside the established deadlines cannot be addressed, which will imply the total loss of the amount paid.</p>
                  <p><strong>7.3. Management by OASIX.</strong> When appropriate, OASIX will act as an intermediary to manage with the provider the modification, rescheduling, or, where appropriate, the partial or total refund of the contracted service. The final acceptance of the cancellation or modification will always depend on the provider's policies. OASIX commits to communicating to the User, within a reasonable time, the resolution adopted by the provider.</p>
                  <p><strong>7.4. Non-refundable services.</strong> There are services, deposits, or set-asides that may be non-refundable, which will be informed to the User prior to the confirmation of the contracting. Examples: Reservations on high-demand dates (e.g., 2026 World Cup matches, special events, national holidays); Services with limited capacity or requiring advance payment for artists, guides, or venues; Deposits intended to secure availability. In these cases, cancellation by the User will not result in any refund, regardless of the cause invoked.</p>
                  <p><strong>7.5. Refund method.</strong> When applicable, refunds will be made using the same payment method used by the User. If not technically possible, OASIX may process the refund via bank transfer to an account under the name of the original reservation holder. The refunded amount will only correspond to the amount effectively paid by the User to OASIX, excluding financial expenses, bank commissions, or additional costs assumed by the User.</p>
                  <p><strong>7.6. Crediting periods.</strong> Refund crediting times will depend on the deadlines established by financial institutions, extending between 5 and 20 business days counted from the confirmation of the refund's validity.</p>
                  <p><strong>7.7. Limitation of liability.</strong> The User acknowledges and accepts that: OASIX cannot guarantee refunds when providers determine that the refund does not apply; OASIX will not be responsible for delays attributable to financial institutions or payment gateways; Under no circumstances will amounts corresponding to additional consumptions, tips, transportation costs, or other services not directly contracted with OASIX be refunded.</p>

                  <h2>8. User Obligations</h2>
                  <p>The User, upon contracting and using OASIX Services, expressly accepts the following obligations:</p>
                  <p><strong>8.1. Truthfulness and accuracy of information.</strong> Provide truthful, complete, accurate, and updated data at all times. Immediately notify any error or omission detected in the data sent to OASIX. Acknowledge that any inaccuracy, falsehood, or omission will be the exclusive responsibility of the User and may result in the cancellation of the Service without the right to a refund.</p>
                  <p><strong>8.2. Compliance with specific requirements.</strong> Prove, when applicable, the minimum age requirements, documentation (ID, passport, visa, medical proofs, vaccination certificates, etc.), or security conditions required for the contracted Service. Follow the instructions, restrictions, and recommendations indicated by OASIX or the providers during the experience. In the case of minors, ensure they participate under the direct supervision of a responsible adult.</p>
                  <p><strong>8.3. Respect for policies and rules of coexistence.</strong> Respect the policies of conduct, hygiene, dress code, safety, coexistence, and punctuality established by OASIX, by the contracted providers, restaurants, bars, or venues. Refrain from inappropriate, aggressive, discriminatory behaviors or those that alter the order and safety of the event. Comply with health, civil protection, and safety regulations issued by authorities or providers. Non-compliance with these policies will entitle OASIX or the provider to deny access, remove the User from the event, or cancel the Service provision, without an obligation to refund.</p>
                  <p><strong>8.4. Responsibility for additional expenses.</strong> Fully assume transportation costs to and from the meeting point, unless expressly included in the package. Cover tips, additional consumptions, beverages, food, souvenirs, or other expenses not contemplated in the initial contract. Acknowledge that these expenses are not OASIX's responsibility.</p>
                  <p><strong>8.5. Prohibition of unauthorized resale or assignment.</strong> Do not resell, transfer, assign, or market reservations without prior express authorization from OASIX. Acknowledge that any unauthorized attempt to resell or assign will automatically invalidate the reservation, without the right to a refund.</p>
                  <p><strong>8.6. Responsible consumption of alcohol and substances.</strong> In experiences that include the consumption of alcoholic beverages (e.g., tastings, fan zones, gastronomic tours), do so responsibly and in accordance with local laws. The consumption of drugs, narcotics, or illegal substances is prohibited in all Services managed by OASIX. Non-compliance will entitle OASIX or the provider to deny access or remove the User from the event without the right to a refund.</p>
                  <p><strong>8.7. Punctuality and attendance.</strong> Appear punctually at the place, date, and time indicated in the reservation confirmation. Acknowledge that Services have a fixed start time and that tardiness may result in the partial or total loss of the experience without the right to a refund.</p>
                  <p><strong>8.8. Damages and personal liability.</strong> Care for and properly use the facilities, furniture, equipment, transport, materials, and objects made available during the experience. Financially respond for damages caused maliciously or negligently to third parties, facilities, furniture, or equipment used in the experience.</p>
                  <p><strong>8.9. Acceptance of consequences for non-compliance.</strong> The User's failure to comply with any of the obligations provided herein will entitle OASIX and/or the providers to: Cancel the contracted Service without the right to a refund; Deny access to the event or experience; Request compensation for damages caused; Exercise corresponding legal actions to protect their rights.</p>

                  <h2>9. Limitation of liability</h2>
                  <p><strong>9.1. Nature of OASIX's intervention.</strong> The User acknowledges and accepts that OASIX acts as a manager, organizer, and in many cases as an intermediary between the User and external service providers (restaurants, bars, venues, guides, transporters, artists, tourist sites, among others). Therefore, the correct execution of certain services depends directly on said providers, whose internal policies are binding for the User.</p>
                  <p><strong>9.2. Liability Exclusions.</strong> OASIX will not be responsible, under any circumstances, for: Cancellations, delays, failures, or deficiencies attributable to external providers contracted for the partial or total execution of the Service; Adverse weather conditions, natural phenomena, force majeure events, or unforeseeable circumstances affecting the execution of the Service; Health situations, government restrictions, or public safety measures that prevent or limit the development of the Service; Loss, theft, or damage of the User's personal belongings before, during, or after the Service; Accidents, injuries, illnesses, or damages caused by the negligence, recklessness, failure to follow instructions, or health condition of the User; Indirect damages, loss of opportunity, business expectations, future income, collateral expenses, or any form of lost profits.</p>
                  <p><strong>9.3. Risks assumed by the User.</strong> The User acknowledges and accepts that participating in gastronomic, cultural, entertainment experiences, or sporting events carries certain inherent risks, which include, but are not limited to: Dietary risks (allergies, intolerances, poisoning); Physical risks (falls, minor or major injuries in recreational, sports, or transportation activities); Risks associated with alcohol consumption; Risks of interacting with crowds or mass events. The User declares to be aware of these risks and assumes full responsibility for their participation in the contracted experiences.</p>
                  <p><strong>9.4. Quantitative limitation of liability.</strong> In any case, OASIX's maximum liability to the User will be strictly limited to the amount effectively paid by the User for the specific contracted Service that gave rise to the claim. Under no circumstances will compensations for higher amounts, punitive damages, or additional compensations proceed. If the claim involves a third-party provider, any potential liability will be subject to the policies and legal limitations of said provider.</p>
                  <p><strong>9.5. Exoneration in case of User non-compliance.</strong> OASIX will not be responsible for the total or partial non-compliance of the Service when it derives from: The User's lack of punctuality; Non-compliance with access requirements (documentation, minimum age, dress code); Omission of previously notified medical, health, or safety restrictions; Inappropriate, negligent, or illicit conduct by the User or their companions.</p>
                  <p><strong>9.6. Indemnity.</strong> The User agrees to hold OASIX harmless from any claim, demand, procedure, or judicial action filed by third parties derived from acts or omissions of the User themselves during the execution of the Service.</p>

                  <h2>10. Intellectual Property</h2>
                  <p><strong>10.1. Ownership of rights.</strong> All content available on OASIX's sites, platforms, and promotional materials—including, without limitation, texts, service descriptions, graphic material, logos, registered trademarks, trade names, photographs, images, audios, videos, designs, icons, interfaces, source codes, and any other element protected by intellectual or industrial property rights—are the exclusive property of GREATDEN, S.A. DE C.V. or of third-party licensors who have authorized their use.</p>
                  <p><strong>10.2. Legal protection.</strong> Such content is protected by national and international legislation regarding copyright, industrial property, and intellectual property, including, but not limited to: The Federal Copyright Law of Mexico; The Industrial Property Law of Mexico; International treaties signed by the United Mexican States, such as the Berne Convention, TRIPS, and WIPO treaties.</p>
                  <p><strong>10.3. Limited use license.</strong> Access to the website and OASIX materials does not grant the User any right of exploitation over the contents, except for a personal, limited, non-exclusive, revocable, and non-transferable use license, whose sole purpose is to allow the proper contracting and enjoyment of the services.</p>
                  <p><strong>10.4. Prohibited uses.</strong> It is strictly prohibited, without prior written authorization from OASIX, to: Reproduce, copy, distribute, publicly communicate, transform, modify, translate, adapt, decompile, extract, or use the protected content for commercial or promotional purposes; Use OASIX logos, trade names, trademarks, or distinctive signs for advertising, commercial, or association purposes without express consent; Generate derivative works, mirror sites, resell content, scrape, or extract databases belonging to OASIX.</p>
                  <p><strong>10.5. Third-party content and licenses.</strong> In the event that some content, photographs, images, videos, or materials belong to third parties and are used under licenses, assignments, or authorizations, such rights will correspond to their respective owners. The User agrees to fully respect such rights and not perform acts that violate their legal protection.</p>
                  <p><strong>10.6. Infringements.</strong> Any unauthorized use of the content owned by OASIX or its licensors will constitute an infringement of intellectual and industrial property rights, which may lead to: The demand for civil liability for damages; The exercise of civil, administrative, and/or criminal legal actions in accordance with applicable legislation; The immediate suspension of accesses or contracted services, without obligation to refund.</p>
                  <p><strong>10.7. Collaborations and content assignment.</strong> In the event that a User participates in content co-creation activities (e.g., photographs, testimonials, recordings on tours or fan zones), they grant OASIX, free of charge, a non-exclusive, transferable, sublicensable, global, and indefinite license to use, reproduce, publicly communicate, distribute, and transform said content, solely and exclusively for promotional, commercial, or advertising purposes related to OASIX services.</p>

                  <h2>12. Applicable law and jurisdiction</h2>
                  <p><strong>12.1.</strong> These General Conditions shall be governed by the laws of the United Mexican States.</p>
                  <p><strong>12.2.</strong> For any dispute arising from the interpretation or execution of these Conditions, the parties submit to the competent courts of Mexico City, expressly waiving any other jurisdiction that may correspond to them.</p>

                  <h2>13. Final provisions</h2>
                  <p><strong>13.1. Modification power.</strong> OASIX reserves the right to modify, update, or complement these General Conditions at any time, whether due to regulatory changes, internal operational adjustments, or improvements in service provision. The updated version will be published on the official OASIX website and will replace the previous one as of its publication date.</p>
                  <p><strong>13.2. User's responsibility.</strong> It will be the exclusive responsibility of the User to periodically review the current General Conditions before contracting or using any service. Contracting following the publication of modifications will constitute full, express, and unconditional acceptance of such modifications.</p>
                  <p><strong>13.3. Binding nature.</strong> The User acknowledges that these General Conditions, together with the specific conditions of each Service, constitute the entire, unique, and binding agreement between the parties, superseding any prior communication, proposal, or understanding, whether verbal or written.</p>
                  <p><strong>13.4. Severability.</strong> If any provision of these Conditions is declared null, illegal, or inapplicable by a competent authority, such nullity or inapplicability will not affect the validity and enforceability of the remaining clauses, which will remain in full force and effect.</p>
                  <p><strong>13.5. Non-waiver of rights.</strong> The failure or delay of OASIX in exercising any right or power derived from these Conditions will not constitute a waiver thereof, nor will it prevent its subsequent exercise.</p>
                  <p><strong>13.6. Language.</strong> In the event of a discrepancy between the Spanish version and a possible translation into another language of these Conditions, the Spanish version shall always prevail.</p>
                  <p><strong>13.7. Validity.</strong> These General Conditions will be in force from their publication date on the official OASIX website and will remain applicable until replaced by a new version.</p>
                </>
              )}
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
